// Plain-English "what is this league/series?" blurbs, keyed by catalog ref.
// Surfaced by the ⓘ button on each Discover card so abbreviations aren't a mystery.
export const LEAGUE_INFO: Record<string, string> = {
  // ---- Motorsport ----
  current: "Formula 1 — the pinnacle of open-wheel racing. ~20 drivers and 10 teams contest ~24 Grands Prix worldwide for the World Championship.",
  "racing/f1": "Formula 1 — the pinnacle of open-wheel racing; ~24 global Grands Prix.",
  "racing/irl": "IndyCar — America's top open-wheel series, mixing ovals, road and street courses. Home of the Indianapolis 500.",
  "racing/nascar-premier": "NASCAR Cup Series — the top US stock-car championship; 36 races, mostly ovals, kicking off with the Daytona 500.",
  "racing/nascar-secondary": "NASCAR Xfinity Series — NASCAR's second tier, one step below the Cup Series.",
  "racing/nascar-truck": "NASCAR Craftsman Truck Series — pickup-truck racing, NASCAR's third national division.",
  motogp: "MotoGP — the premier class of motorcycle Grand Prix racing on ~1000cc prototype bikes; the fastest riders in the world.",
  moto2: "Moto2 — the feeder class below MotoGP, run on spec 765cc engines.",
  moto3: "Moto3 — the entry Grand Prix motorcycle class; 250cc single-cylinder bikes and the youngest riders.",
  "4409": "WRC — the FIA World Rally Championship. Factory-backed cars race timed stages on gravel, snow and tarmac across the world.",
  "4371": "Formula E — the FIA's all-electric single-seater championship, raced on temporary street circuits in major cities.",
  "4486": "Formula 2 — the main feeder series to F1; spec cars in support races on Grand Prix weekends.",
  "4487": "Formula 3 — a rung below F2 on the road to F1, for young drivers in spec single-seaters.",
  "5382": "F1 Academy — an all-female single-seater series developing drivers toward Formula 1.",
  "4454": "WSBK — the Superbike World Championship, raced on production-derived sportbikes.",
  "5264": "BSB — the British Superbike Championship, the UK's premier production-bike series.",
  "4372": "BTCC — the British Touring Car Championship. Close, contact-heavy racing in modified road cars.",
  "4438": "DTM — a German-based GT3 touring/sports-car championship (Deutsche Tourenwagen Masters).",
  "4489": "Supercars — Australia's premier touring-car series with V8 muscle cars; home of the Bathurst 1000.",
  "4468": "AMA Supercross — indoor stadium motocross on man-made dirt tracks, on 450cc bikes.",
  "4469": "Pro Motocross — the AMA's outdoor motocross championship on natural-terrain tracks.",
  "5412": "SuperMotocross — a playoff series crowning one champion across Supercross and Pro Motocross.",
  "5309": "NHRA — top US drag racing. Top Fuel and Funny Cars sprint in a straight line in under 4 seconds.",
  "5094": "ARCA Menards Series — a NASCAR-sanctioned stock-car development series.",
  "4730": "World RX — the FIA World Rallycross Championship; short, wheel-to-wheel races on mixed tarmac/gravel circuits.",
  "4712": "Extreme E — off-road racing in electric SUVs held in remote, environmentally challenged locations.",
  "4447": "Dakar Rally — a two-week off-road rally-raid across desert terrain for cars, bikes, trucks and quads.",
  "4732": "Isle of Man TT — time-trial motorcycle races on closed public roads; one of the fastest, most dangerous events in the sport.",
  "4440": "GT World Challenge — GT3 sports-car racing (SRO) across sprint and endurance rounds.",
  "5491": "FIM EWC — the Endurance World Championship for motorcycles, with marathons like the Suzuka 8 Hours.",

  // ---- Team sports ----
  "hockey/nhl": "NHL — the National Hockey League, the top men's ice-hockey league (US & Canada).",
  "basketball/nba": "NBA — the National Basketball Association, the world's top men's basketball league.",
  "basketball/wnba": "WNBA — the top women's professional basketball league in the US.",
  "football/nfl": "NFL — the National Football League, the top American-football league.",
  "baseball/mlb": "MLB — Major League Baseball, the top US/Canada baseball league.",
  "soccer/eng.1": "Premier League — England's top men's football division.",
  "soccer/esp.1": "La Liga — Spain's top men's football division.",
  "soccer/ger.1": "Bundesliga — Germany's top men's football division.",
  "soccer/ita.1": "Serie A — Italy's top men's football division.",
  "soccer/fra.1": "Ligue 1 — France's top men's football division.",
  "soccer/usa.1": "MLS — Major League Soccer, the top league in the US and Canada.",
  "soccer/mex.1": "Liga MX — Mexico's top men's football division.",
  "soccer/uefa.champions": "UEFA Champions League — Europe's elite club competition, the biggest prize in club football.",
  "soccer/uefa.europa": "UEFA Europa League — Europe's second-tier club competition.",
  "soccer/uefa.europa.conf": "UEFA Conference League — Europe's third-tier club competition.",
  "soccer/usa.nwsl": "NWSL — the National Women's Soccer League, the top US women's league.",
  "soccer/eng.2": "EFL Championship — England's second football division, below the Premier League.",
  "soccer/ned.1": "Eredivisie — the Netherlands' top men's football division.",
  "soccer/por.1": "Primeira Liga — Portugal's top men's football division.",
  "soccer/sco.1": "Scottish Premiership — Scotland's top men's football division.",
  "soccer/tur.1": "Süper Lig — Turkey's top men's football division.",
  "soccer/bra.1": "Brasileirão — Brazil's top men's football division (Série A).",
  "soccer/arg.1": "Liga Profesional — Argentina's top men's football division.",
  "soccer/ksa.1": "Saudi Pro League — Saudi Arabia's top men's football division.",
  "soccer/jpn.1": "J.League — Japan's top men's football division.",
  "soccer/aus.1": "A-League Men — Australia's top men's football division.",
  "soccer/eng.w.1": "Women's Super League — England's top women's football division.",
  "soccer/eng.fa": "FA Cup — England's historic knockout football competition, open to clubs at every level.",
  "soccer/eng.league_cup": "Carabao Cup — England's secondary knockout cup (the EFL Cup).",
  "soccer/conmebol.libertadores": "Copa Libertadores — South America's elite club competition.",
  "soccer/concacaf.champions_cup": "CONCACAF Champions Cup — the top club competition of North/Central America and the Caribbean.",
  "australian-football/afl": "AFL — the Australian Football League, the top competition of Australian-rules football.",
  "rugby-league/3": "NRL — Australia's National Rugby League, the top rugby-league competition.",
  "rugby/267979": "Premiership Rugby — England's top rugby-union league.",
  "rugby/242041": "Super Rugby Pacific — the top club rugby-union competition across Australia, NZ and the Pacific.",
  "rugby/270557": "United Rugby Championship — club rugby union across Ireland, Wales, Scotland, Italy and South Africa.",
  "rugby/180659": "Six Nations — the annual rugby-union championship between England, France, Ireland, Italy, Scotland and Wales.",
  "lacrosse/pll": "PLL — the Premier Lacrosse League, the top US men's field-lacrosse league.",
  "football/college-football": "College Football — US NCAA university football (FBS).",
  "basketball/mens-college-basketball": "NCAA Men's Basketball — US college basketball, home of March Madness.",
  "basketball/womens-college-basketball": "NCAA Women's Basketball — US college women's basketball.",
  "baseball/college-baseball": "NCAA Baseball — US college baseball, culminating in the College World Series.",
  "baseball/college-softball": "NCAA Softball — US college softball, culminating in the Women's College World Series.",
  "hockey/mens-college-hockey": "NCAA Men's Ice Hockey — US college hockey (the Frozen Four).",
  "hockey/womens-college-hockey": "NCAA Women's Ice Hockey — US college women's hockey.",
  "volleyball/womens-college-volleyball": "NCAA Women's Volleyball — US college women's volleyball.",
  "volleyball/mens-college-volleyball": "NCAA Men's Volleyball — US college men's volleyball.",
  "lacrosse/mens-college-lacrosse": "NCAA Men's Lacrosse — US college men's lacrosse.",

  // ---- Individual / event sports ----
  "tennis/atp": "ATP Tour — the top men's professional tennis circuit.",
  "tennis/wta": "WTA Tour — the top women's professional tennis circuit.",
  "golf/pga": "PGA Tour — the top men's professional golf tour, mostly US-based.",
  "golf/lpga": "LPGA Tour — the top women's professional golf tour.",
  "golf/eur": "DP World Tour — the European Tour, top men's golf outside the US.",
  "golf/liv": "LIV Golf — a breakaway 54-hole, shotgun-start men's team league backed by Saudi PIF.",
  "golf/champions-tour": "PGA Tour Champions — the senior men's tour for players aged 50 and over.",
  "mma/ufc": "UFC — the Ultimate Fighting Championship, the leading mixed martial arts (MMA) promotion.",
  "mma/pfl": "PFL — the Professional Fighters League, MMA run as a season-long tournament.",
  "4445": "Boxing — major professional boxing cards and title fights worldwide.",
  "8048": "IPL — the Indian Premier League, the biggest Twenty20 (T20) franchise cricket league.",
  "8044": "Big Bash League — Australia's Twenty20 (T20) franchise cricket league.",
  "4554": "PDC Darts — the Professional Darts Corporation tour, incl. the World Championship at Alexandra Palace.",
  "4555": "World Snooker — the professional snooker tour, incl. the World Championship at the Crucible.",
  "5007": "World Athletics Championships — the global track-and-field championships: sprints, distance, jumps and throws.",

  // ---- Other ----
  upcoming: "Upcoming movies — new theatrical releases, so you can track opening dates.",
};

/** Blurb for a league/series ref (team refs fall back to their parent league). */
export function leagueBlurb(ref: string | null | undefined): string | undefined {
  if (!ref) return undefined;
  if (LEAGUE_INFO[ref]) return LEAGUE_INFO[ref];
  // A followed team's ref looks like "hockey/nhl/teams/17" — describe its league.
  if (ref.includes("/teams/")) return LEAGUE_INFO[ref.split("/teams/")[0]];
  return undefined;
}
